name: simple_math_counter
description: This is very simple math counter.
version: 1.7.0
repository: https://github.com/mhm-maulanayusuf/simple_math_counter

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
